import "./globals.css";
import { Open_Sans } from "next/font/google";

const googleFont = Open_Sans({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Portifolio Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${googleFont.className} min-h-[100%] bg-gradient-to-br from-pink-400 via-purple-400 to-indigo-400 overflow-y-auto`}
      >
        {children}
      </body>
    </html>
  );
}
