import "./globals.css";
import { Roboto, Montserrat } from "next/font/google";

const roboto300 = Roboto({
  weight: "300",
  subsets: ["latin"],
  variable: "--font-robot-300",
});
const roboto400 = Roboto({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-robot-400",
});
const montserrat = Montserrat({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Portifolio Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${roboto300.className}  ${roboto300.variable} ${roboto400.variable} ${montserrat.variable} min-h-[100%] bg-gradient-to-br from-pink-400 via-purple-400 to-indigo-400 overflow-y-auto`}
      >
        {children}
      </body>
    </html>
  );
}
